<a href="https://colab.research.google.com/github/swopnimghimire-123123/data-analysis-visualization/blob/main/02_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

### **Creating a DataFrame**

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [ ]:
df = pd.DataFrame(data)
print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [ ]:
df2 = pd.DataFrame(data_list)
print(df2)
df3 = pd.DataFrame(data_list, columns=['Name', 'Age', 'City', 'Salary'])
print("\n",df3)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

     Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### **Selection and indexing of columns**

In [ ]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df3[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [ ]:
df3["Destination"] = ["Dcotors","Eng.","Eng.","Actor"]

In [ ]:
df3

    Name  Age      City  Salary Destination
0   John   28  New York   65000     Dcotors
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000        Eng.
3  Linda   42    London   85000       Actor

##**Remvoing Columns**

In [ ]:
# axis = 0 removes the third row that contians Linda data
df2.drop(3,axis=0)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000

In [ ]:
df3.drop("Salary",axis=1)

    Name  Age      City Destination
0   John   28  New York     Dcotors
1   Anna   34     Paris        Eng.
2  Peter   29    Berlin        Eng.
3  Linda   42    London       Actor

### **Selecting Rows**

In [ ]:
df3

    Name  Age      City  Salary Destination
0   John   28  New York   65000     Dcotors
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000        Eng.
3  Linda   42    London   85000       Actor

In [ ]:
df3.loc[[0,1]]

   Name  Age      City  Salary Destination
0  John   28  New York   65000     Dcotors
1  Anna   34     Paris   70000        Eng.

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

###**Selecting Subset of rows and columns**

In [ ]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

###**Conditional Selection**

In [ ]:
df3

    Name  Age      City  Salary Destination
0   John   28  New York   65000     Dcotors
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000        Eng.
3  Linda   42    London   85000       Actor

In [ ]:
# I Only want to see those people whose age is above 30

In [ ]:
df3[df3["Age"]>30]

    Name  Age    City  Salary Destination
1   Anna   34   Paris   70000        Eng.
3  Linda   42  London   85000       Actor

In [ ]:
# I Only want those poeple whose age is above 30 and their city must be paris
df3[(df3["Age"]>30) & (df3["City"]== "Paris")]

   Name  Age   City  Salary Destination
1  Anna   34  Paris   70000        Eng.