<a href="https://colab.research.google.com/github/swopnimghimire-123123/data-analysis-visualization/blob/main/07_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

###**DataFrames Basic Operations**

In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1.shape

(5, 3)

In [ ]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1["A"] + 100

0    101
1    102
2    103
3    104
4    105
Name: A, dtype: int64

In [ ]:
df1+10

    A   B    C
0  11  20  110
1  12  30  210
2  13  40  310
3  14  50  410
4  15  60  510

###**DataFrames Applying Functions**

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1["D"] = df1["B"].apply(lambda x: x**2)

In [ ]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [ ]:
df1["E"]=df1["A"].apply(lambda x: x**2)

In [ ]:
df1

   A   B    C     D   E
0  1  10  100   100   1
1  2  20  200   400   4
2  3  30  300   900   9
3  4  40  400  1600  16
4  5  50  500  2500  25

In [ ]:
df1["F"]=[45,33,55,66,44]
df1

   A   B    C     D   E   F
0  1  10  100   100   1  45
1  2  20  200   400   4  33
2  3  30  300   900   9  55
3  4  40  400  1600  16  66
4  5  50  500  2500  25  44